############################################################################
#  Makefile: Particular Makefile in approach
#  Copyright (C) 2012 Brno University of Technology, ANT @ FIT
#  Author(s): Milan Pala, xpalam00@stud.fit.vutbr.cz
############################################################################

# Include base Makefile with common targets
include ../../Makefile.inc

# Name of approach used in his filenames
# e.g.: hybrid_fa.py -> hybrid_fa
# APPROACH_NAME=clark_nfa

CLEAN += test/*.vhd test/*.tcl *.vhd test/transcript test/vsim.wlf test/work test/*~ 
PM_BASE  = ../..
DOC_NAME = pattern_match.algorithms.clark_nfa.html